// <auto-generated />
namespace AnswerSpaTest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201507270850350_InitialUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
